/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alban
 */
public class EcranAccueil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EcranAccueil.class.getName());

    /**
     * Creates new form EcranAccueil
     */
    public EcranAccueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Facile = new javax.swing.JButton();
        btn_Normal = new javax.swing.JButton();
        btn_Difficile = new javax.swing.JButton();
        Texte_Début = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Facile.setText("Jouer Facile");
        btn_Facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FacileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Facile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, -1));

        btn_Normal.setText("Jouer Normal");
        btn_Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NormalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        btn_Difficile.setText("Jouer Difficile");
        btn_Difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DifficileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Difficile, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        Texte_Début.setFont(new java.awt.Font("Stencil", 3, 24)); // NOI18N
        Texte_Début.setForeground(new java.awt.Color(255, 255, 255));
        Texte_Début.setText("Bienvenue dans le jeu !");
        getContentPane().add(Texte_Début, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 310, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\alban\\OneDrive\\Images\\Pellicule\\2023\\08\\20230809_175518000_iOS 1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FacileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FacileActionPerformed
        Interface i = new Interface();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_FacileActionPerformed

    private void btn_NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NormalActionPerformed
        Interface i = new Interface();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_NormalActionPerformed

    private void btn_DifficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DifficileActionPerformed
        Interface i = new Interface();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_DifficileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EcranAccueil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Texte_Début;
    private javax.swing.JButton btn_Difficile;
    private javax.swing.JButton btn_Facile;
    private javax.swing.JButton btn_Normal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
