
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alban
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private ArrayList<Question> listeQuestions;
    private int indexQuestionCourante = 0;
    private int score = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    
    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();
        initialiserQuestions();
        afficherQuestionCourante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        QuestionSuivante = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestion.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        lblQuestion.setText("Question");
        getContentPane().add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 45, -1, -1));

        btnRep1.setText("Reponse 1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 109, -1, -1));

        btnRep2.setText("Reponse 2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 109, -1, -1));

        btnRep3.setText("Reponse 3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 150, -1, -1));

        btnRep4.setText("Reponse 4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 150, -1, -1));

        lblFeedback.setText("Feedback");
        getContentPane().add(lblFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 262, -1, -1));

        QuestionSuivante.setText("Question suivante");
        QuestionSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionSuivanteActionPerformed(evt);
            }
        });
        getContentPane().add(QuestionSuivante, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 10, -1, -1));

        lblScore.setText("Score :");
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 13, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuestionSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionSuivanteActionPerformed
        indexQuestionCourante++;
        if (indexQuestionCourante < listeQuestions.size()) {
            afficherQuestionCourante();
        } else {
            lblQuestion.setText("FIN DU QUIZ !");
            lblFeedback.setText("Quiz terminé. Score final : " + score + " / " + listeQuestions.size());
            QuestionSuivante.setEnabled(false);
            lblScore.setText("Score final : " + score + " / " + listeQuestions.size());
        }
    }//GEN-LAST:event_QuestionSuivanteActionPerformed

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        verifierReponse(1);
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        verifierReponse(2);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        verifierReponse(3);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        verifierReponse(4);
    }//GEN-LAST:event_btnRep4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuestionSuivante;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

private void initialiserQuestions() {
        listeQuestions = new ArrayList<>();
       
        listeQuestions.add(new Question(
            "Quelle est la planète la plus proche du Soleil ?",
            "Terre", "Mercure", "Mars", "Vénus", 2));
        listeQuestions.add(new Question(
            "Qui a écrit Les Misérables ?",
            "Victor Hugo", "Emile Zola", "Molière", "Albert Camus", 1));
        listeQuestions.add(new Question(
            "Quel est le plus grand océan du monde ?",
            "Atlantique", "Artique", "Idien", "Pacifique", 4));
        listeQuestions.add(new Question(
            "Combien vaut la racine carrée de 144 ?",
            "10", "11", "12", "14", 3));
        listeQuestions.add(new Question(
            "Quelle est la capitale de l’Italie ? ?",
            "Naples", "Rome", "Turin", "Milan", 2));
    }

 private void afficherQuestionCourante() {
        if (indexQuestionCourante >= listeQuestions.size()) {
            return;
        }

Question question = listeQuestions.get(indexQuestionCourante);
       
        lblQuestion.setText(question.getIntitule());
       
        btnRep1.setText(question.getProposition1());
        btnRep2.setText(question.getProposition2());
        btnRep3.setText(question.getProposition3());
        btnRep4.setText(question.getProposition4());
       
        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);
       
        QuestionSuivante.setEnabled(false);
       
        lblFeedback.setText("Choisissez une réponse...");
        lblScore.setText("Score : " + score + " / " + listeQuestions.size());
    }

 private void verifierReponse(int reponseChoisie) {
        Question questionCourante = listeQuestions.get(indexQuestionCourante);

        if (reponseChoisie == questionCourante.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !!");
            score++;
        } else {
            lblFeedback.setText("Mauvaise réponse. La bonne réponse était la proposition " + questionCourante.getIndexBonneReponse() + ".");
        }
        
 btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
       
        QuestionSuivante.setEnabled(true);
       
        lblScore.setText("Score : " + score + " / " + (indexQuestionCourante + 1));
    }
}
